version: 2
jobs:
  setup-heroku-cluster:
    working_directory: ~/project
    machine: true
    steps:
    - checkout
    - run:
        name: Provision Heroku Dyno
        command: echo "Spinning up a Heroku Dyno"

  build-node-app:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    parallelism: 2
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Update NPM
        command: 'sudo npm install -g npm@latest'
    - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - node-v1-{{ .Branch }}-
          - node-v1-
    - run:
        name: Fetch dependencies
        command: npm install
    - save_cache:
        paths:
          - node_modules  # location depends on npm version
        key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
    - run:
        name: Test application - leverage test splitting
        command: echo "Testing"
    - run:
        name: Build Docker Image # step & job names should never be the same
        command: docker build -t registry.heroku.com/damp-bastion-21277/web:${CIRCLE_SHA1} \
                 --build-arg CIRCLE_SHA1=$CIRCLE_SHA1 \
                 --build-arg CIRCLE_BUILD_URL=$CIRCLE_BUILD_URL .
  
  code-linting:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
  code-coverage:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
  vulnerability-scans:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout

  build-docker-image:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout  
    - setup_remote_docker
    # these cached dependencies
    - run:
        name: Fetch dependencies
        command: npm install
    # think about caching here too
    - run:
        name: Populate Metadata
        command: env | grep -i circle > env
    - run:
        name: Verify Metadata
        command: cat env
    - run:
        name: Build Docker Image # step & job names should never be the same
        command: docker build -t registry.heroku.com/damp-bastion-21277/web:${CIRCLE_SHA1} \
                 --build-arg CIRCLE_SHA1=$CIRCLE_SHA1 \
                 --build-arg CIRCLE_BUILD_URL=$CIRCLE_BUILD_URL .
    - run:
        name: Export Docker image as tar file
        command: docker save registry.heroku.com/damp-bastion-21277/web:${CIRCLE_SHA1} > image.tar
    - run:
        name: Integration Tests
      #  command: docker run circlese:demo
        command: echo "Running Integration Tests"
    - persist_to_workspace:
          root: ~/project
          paths:
            - image.tar


  deploy-application:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    # dubious if this is really needed
    - setup_remote_docker
    - checkout
    - attach_workspace:
          at: ~/project
    - run:
        name: Provision Heroku Dyno
        command: echo "Deploying appication"
    - run:
        name: setup heroku cli
        command: |
          chmod +x scripts/setup_herokucli.sh && scripts/setup_herokucli.sh
    - run:
        name: Update NPM
        command: 'sudo npm install -g npm@latest'
    - run:
        name: Fetch dependencies
        command: npm install
    - run:
        name: Load Docker image from tar file
        command: docker load --input image.tar
    - run:
        name: Build and Tag Docker Image
        command: |
          docker push registry.heroku.com/damp-bastion-21277/web:${CIRCLE_SHA1}
    - run:
        name: Deploy Application
        command: chmod +x scripts/deploy.sh && scripts/deploy.sh $HEROKU_APPLICATION

workflows:
  version: 2
  build-test-&-deploy:
    jobs:
      - build-node-app
      - setup-heroku-cluster
      - code-linting:
          requires:
            - build-node-app
      - code-coverage:
          requires:
            - build-node-app
      - vulnerability-scans:
          requires:
            - build-node-app
      - build-docker-image:
          requires:
            - code-coverage
            - vulnerability-scans
      - deploy-application:
          requires:
            - setup-heroku-cluster
            - build-docker-image
