version: 2
jobs:
  build-node-app:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
    - run:
        name: Update NPM
        command: 'sudo npm install -g npm@latest'
    - run:
        name: Fetch dependencies
        command: npm install
    - run:
        name: Test application
        # command: node app.js
        command: echo "start app here"
  
  code-linting:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
  code-coverage:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
  vulnerability-scans:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout

  build-docker-image:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - setup_remote_docker
    - checkout
    # these cached dependencies
    - run:
        name: Fetch dependencies
        command: npm install
    # think about caching here too
    - run:
        name: Build Docker Image
        command: docker build -t circlese:demo .
    - run:
        name: Integration Tests
      #  command: docker run circlese:demo
        command: echo "Running Integration Tests"
    - run:
          name: setup heroku cli
          command: |
            chmod +x scripts/setup_herokucli.sh && scripts/setup_herokucli.sh
    - run: docker build -t registry.heroku.com/damp-bastion-21277/web:${CIRCLE_SHA1} .
    - run: docker push registry.heroku.com/damp-bastion-21277/web:${CIRCLE_SHA1}

  setup-heroku-cluster:
    working_directory: ~/project
    machine: true
    steps:
    - checkout
    - run:
        name: Provision Heroku Dyno
        command: echo "Spinning up a Heroku Dyno"

  deploy-application:
    working_directory: ~/project
    machine: true
    steps:
    - checkout
    - run:
        name: Provision Heroku Dyno
        command: echo "Deploying appication"

workflows:
  version: 2
  build-test-&-deploy:
    jobs:
      - build-node-app
      - setup-heroku-cluster
      - code-linting:
          requires:
            - build-node-app
      - code-coverage:
          requires:
            - build-node-app
      - vulnerability-scans:
          requires:
            - build-node-app
      - build-docker-image:
          requires:
            - code-coverage
            - vulnerability-scans
      - deploy-application:
          requires:
            - setup-heroku-cluster
            - build-docker-image
